---
platform: linux
image_resource: 
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: 2.2-sdk
inputs:
  - name: source
run:
  path: /bin/sh
  args:
  - -c
  - |
    cd source/PdfSharp
    dotnet build /p:GeneratePackageOnBuild=False -c Release PdfSharp.csproj
